services:
  pub:
    image: goosecraft:6.2.1
    stop_grace_period: 2m
    ports:
      - "25575:25565/tcp"
    restart: unless-stopped
    volumes:
      - pub-world:/server/world
      - pub-schematics:/server/schematics
      - pub-logs:/server/logs
      - pub-crash-reports:/server/crash-reports
      - pub-backups:/server/backups
      - pub-cache:/server/.cache
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  dev:
    image: goosecraft:6.2.1
    stop_grace_period: 2m
    ports:
      - "25576:25565/tcp"
    restart: unless-stopped
    volumes:
      - dev-world:/server/world
      - dev-schematics:/server/schematics
      - dev-logs:/server/logs
      - dev-crash-reports:/server/crash-reports
      - dev-backups:/server/backups
      - dev-cache:/server/.cache
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  pub-world:
  pub-schematics:
  pub-logs:
  pub-crash-reports:
  pub-backups:
  pub-cache:
  dev-world:
  dev-schematics:
  dev-logs:
  dev-crash-reports:
  dev-backups:
  dev-cache:
