services:
  pub:
    image: goosecraft:6.6.0
    stop_grace_period: 2m
    ports:
      - "25565:25565/tcp"
    restart: unless-stopped
    volumes:
      - /data/volumes/minecraft/pub/world:/server/world
      - /data/volumes/minecraft/pub/schematics:/server/schematics
      - /data/volumes/minecraft/pub/logs:/server/logs
      - /data/volumes/minecraft/pub/crash-reports:/server/crash-reports
      - /data/volumes/minecraft/pub/backups:/server/backups
      - /data/volumes/minecraft/pub/cache:/server/.cache
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  dev:
    image: goosecraft:6.6.0
    stop_grace_period: 2m
    ports:
      - "25566:25565/tcp"
    restart: unless-stopped
    volumes:
      - /data/volumes/minecraft/dev/world:/server/world
      - /data/volumes/minecraft/dev/schematics:/server/schematics
      - /data/volumes/minecraft/dev/logs:/server/logs
      - /data/volumes/minecraft/dev/crash-reports:/server/crash-reports
      - /data/volumes/minecraft/dev/backups:/server/backups
      - /data/volumes/minecraft/dev/cache:/server/.cache
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
