version: "3"
services:
  sql:
    image: mysql:latest
    stop_grace_period: 1m
    ports:
      - "25574:3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
      MYSQL_DATABASE: mc
      MYSQL_USER: herobrine
      MYSQL_PASSWORD: ${SQL_PASS}
    volumes:
      - sql-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  pub:
    image: goosecraft:6.1.2
    stop_grace_period: 1m
    ports:
      - "25575:25565/tcp"
    restart: unless-stopped
    volumes:
      - /mnt/md2/pnd/mc/live/pub/world:/server/world
      - /mnt/md2/pnd/mc/live/pub/schematics:/server/schematics
      - /mnt/md2/pnd/mc/live/pub/logs:/server/logs
      - /mnt/md2/pnd/mc/live/pub/crash:/server/crash-reports
      - /mnt/md2/pnd/mc/live/pub/backups:/server/backups
      - /mnt/md2/pnd/mc/live/pub/cache:/server/.cache
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  dev:
    image: goosecraft:6.1.2
    stop_grace_period: 1m
    ports:
      - "25576:25565/tcp"
    restart: unless-stopped
    volumes:
      - /mnt/md2/pnd/mc/live/dev/world:/server/world
      - /mnt/md2/pnd/mc/live/dev/schematics:/server/schematics
      - /mnt/md2/pnd/mc/live/dev/logs:/server/logs
      - /mnt/md2/pnd/mc/live/dev/crash:/server/crash-reports
      - /mnt/md2/pnd/mc/live/dev/backups:/server/backups
      - /mnt/md2/pnd/mc/live/dev/cache:/server/.cache
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  sql-data:
