[display]
	ignore_rarity = false
	draw_sprites = true
	background = "NONE"
	inventory_count = true
	default_color = "WHITE"
	display_single_count = true
	scale = 6
	screen_corner = "BOTTOM_LEFT"
	max_height = 0.5
	display_amount = "TEXT"
	offset_x = 8
	offset_y = 4

[general]

	experience_value = true
	include_items = true
	include_experience = true
	disable_in_creative = false
	force_client_only = false
	include_arrows = true

[behavior]

	move_time = 20
	fade_away = true
	combine_entries = true
	display_time = 80
	move_out_of_screen = true
